services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kms-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: sh
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kms-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      # - backend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: sh
    environment:
      - NODE_ENV=development
      # 필요하면 아래처럼 추가
      # - PORT=8080
      - MODEL_URL=http://model:8000
    depends_on:
      - model

  model:
    build:
      context: ./model-server
      dockerfile: Dockerfile
    container_name: kms-model
    ports:
      - "8000:8000"
    volumes:
      - ./model-server:/app
    stdin_open: true
    tty: true
    command: sh
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3:mini
    depends_on:
      - ollama
  
  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql-data:/var/lib/mysql

  ollama:
    image: ollama/ollama:latest
    container_name: kms-ollama
    ports:
      - "11434:11434"   # (선택) 로컬에서 직접 호출/디버깅하려면 열어두기
    volumes:
      - ollama-data:/root/.ollama  # 모델 캐시(다운로드) 영구 보관
    restart: unless-stopped

  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    container_name: kms-trainer
    volumes:
      - ./trainer:/app
      - ./model-server/models:/out   # 학습 결과 저장 위치
    stdin_open: true
    tty: true
    command: sh


volumes:
  frontend_node_modules:
  backend_node_modules:
  mysql-data:
  ollama-data: