services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kms-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: sh
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kms-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      # - backend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: sh
    environment:
      - NODE_ENV=development
      # 필요하면 아래처럼 추가
      # - PORT=8080
      # - MODEL_URL=http://model:8000

  model:
    build:
      context: ./model-server
      dockerfile: Dockerfile
    container_name: kms-model
    ports:
      - "8000:8000"
    volumes:
      - ./model-server:/app
    stdin_open: true
    tty: true
    command: sh

volumes:
  frontend_node_modules:
  backend_node_modules:
